# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/dsgn_can_network_v3/dsgn_can_network_v3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3 || ORIG_REF_NAME==dsgn_can_network_v3}]

# IP: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_processing_system7_0_0/dsgn_can_network_v3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_processing_system7_0_0 || ORIG_REF_NAME==dsgn_can_network_v3_processing_system7_0_0}]

# IP: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_0/dsgn_can_network_v3_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_axi_gpio_0_0 || ORIG_REF_NAME==dsgn_can_network_v3_axi_gpio_0_0}]

# IP: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_processing_system7_0_axi_periph_0/dsgn_can_network_v3_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==dsgn_can_network_v3_processing_system7_0_axi_periph_0}]

# IP: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_rst_processing_system7_0_100M_0/dsgn_can_network_v3_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==dsgn_can_network_v3_rst_processing_system7_0_100M_0}]

# IP: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_1/dsgn_can_network_v3_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_axi_gpio_0_1 || ORIG_REF_NAME==dsgn_can_network_v3_axi_gpio_0_1}]

# IP: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_xbar_0/dsgn_can_network_v3_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_xbar_0 || ORIG_REF_NAME==dsgn_can_network_v3_xbar_0}]

# IP: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_2/dsgn_can_network_v3_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_axi_gpio_0_2 || ORIG_REF_NAME==dsgn_can_network_v3_axi_gpio_0_2}]

# IP: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_xlconcat_0_0/dsgn_can_network_v3_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_xlconcat_0_0 || ORIG_REF_NAME==dsgn_can_network_v3_xlconcat_0_0}]

# IP: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_auto_pc_0/dsgn_can_network_v3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_auto_pc_0 || ORIG_REF_NAME==dsgn_can_network_v3_auto_pc_0}]

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_processing_system7_0_0/dsgn_can_network_v3_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_processing_system7_0_0 || ORIG_REF_NAME==dsgn_can_network_v3_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_0/dsgn_can_network_v3_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_axi_gpio_0_0 || ORIG_REF_NAME==dsgn_can_network_v3_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_0/dsgn_can_network_v3_axi_gpio_0_0_ooc.xdc

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_0/dsgn_can_network_v3_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_axi_gpio_0_0 || ORIG_REF_NAME==dsgn_can_network_v3_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_rst_processing_system7_0_100M_0/dsgn_can_network_v3_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==dsgn_can_network_v3_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_rst_processing_system7_0_100M_0/dsgn_can_network_v3_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==dsgn_can_network_v3_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_rst_processing_system7_0_100M_0/dsgn_can_network_v3_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_1/dsgn_can_network_v3_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_axi_gpio_0_1 || ORIG_REF_NAME==dsgn_can_network_v3_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_1/dsgn_can_network_v3_axi_gpio_0_1_ooc.xdc

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_1/dsgn_can_network_v3_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_axi_gpio_0_1 || ORIG_REF_NAME==dsgn_can_network_v3_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_xbar_0/dsgn_can_network_v3_xbar_0_ooc.xdc

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_2/dsgn_can_network_v3_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_axi_gpio_0_2 || ORIG_REF_NAME==dsgn_can_network_v3_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_2/dsgn_can_network_v3_axi_gpio_0_2_ooc.xdc

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_2/dsgn_can_network_v3_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_network_v3_axi_gpio_0_2 || ORIG_REF_NAME==dsgn_can_network_v3_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_auto_pc_0/dsgn_can_network_v3_auto_pc_0_ooc.xdc

# XDC: bd/dsgn_can_network_v3/dsgn_can_network_v3_ooc.xdc
