# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.cache/wt [current_project]
set_property parent.project_path /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
add_files /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/dsgn_can_network_v3.bd
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_processing_system7_0_0/dsgn_can_network_v3_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_0/dsgn_can_network_v3_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_0/dsgn_can_network_v3_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_0/dsgn_can_network_v3_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_rst_processing_system7_0_100M_0/dsgn_can_network_v3_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_rst_processing_system7_0_100M_0/dsgn_can_network_v3_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_rst_processing_system7_0_100M_0/dsgn_can_network_v3_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_1/dsgn_can_network_v3_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_1/dsgn_can_network_v3_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_1/dsgn_can_network_v3_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_xbar_0/dsgn_can_network_v3_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_2/dsgn_can_network_v3_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_2/dsgn_can_network_v3_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_axi_gpio_0_2/dsgn_can_network_v3_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/ip/dsgn_can_network_v3_auto_pc_0/dsgn_can_network_v3_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/dsgn_can_network_v3_ooc.xdc]
set_property is_locked true [get_files /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/dsgn_can_network_v3.bd]

read_vhdl -library xil_defaultlib /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/sources_1/bd/dsgn_can_network_v3/hdl/dsgn_can_network_v3_wrapper.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top dsgn_can_network_v3_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef dsgn_can_network_v3_wrapper.dcp

catch { report_utilization -file dsgn_can_network_v3_wrapper_utilization_synth.rpt -pb dsgn_can_network_v3_wrapper_utilization_synth.pb }
