webtalk_init -webtalk_dir /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 6 12:21:03 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "u4bfulu7pb9qhna7g7fqsjd6aj" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_22" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1481017702000" -context "sdk\\\\hardware/1481017702000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1481017702000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1481017702000"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.2" -context "sdk\\\\hardware/1481017702000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1481017702000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1481017702000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1481017702000"
webtalk_add_data -client sdk -key uid -value "1481017723000" -context "sdk\\\\bsp/1481017723000"
webtalk_add_data -client sdk -key hwid -value "1481017702000" -context "sdk\\\\bsp/1481017723000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1481017723000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1481017723000"
webtalk_add_data -client sdk -key uid -value "1481017724000" -context "sdk\\\\application/1481017724000"
webtalk_add_data -client sdk -key hwid -value "1481017702000" -context "sdk\\\\application/1481017724000"
webtalk_add_data -client sdk -key bspid -value "1481017723000" -context "sdk\\\\application/1481017724000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1481017724000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1481017724000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1481017724000"
webtalk_transmit -clientid 1215152152 -regid "" -xml /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/catalin/M.E.Electronics/Project_2/SEM2PRO/Vivado/can_network_v3/can_network_v3.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
