# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrains.xdc

# Block Designs: bd/dsgn_can_test_intr/dsgn_can_test_intr.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_test_intr || ORIG_REF_NAME==dsgn_can_test_intr}]

# IP: bd/dsgn_can_test_intr/ip/dsgn_can_test_intr_processing_system7_0_0/dsgn_can_test_intr_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_test_intr_processing_system7_0_0 || ORIG_REF_NAME==dsgn_can_test_intr_processing_system7_0_0}]

# IP: bd/dsgn_can_test_intr/ip/dsgn_can_test_intr_axi_gpio_0_0/dsgn_can_test_intr_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_test_intr_axi_gpio_0_0 || ORIG_REF_NAME==dsgn_can_test_intr_axi_gpio_0_0}]

# IP: bd/dsgn_can_test_intr/ip/dsgn_can_test_intr_processing_system7_0_axi_periph_0/dsgn_can_test_intr_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_test_intr_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==dsgn_can_test_intr_processing_system7_0_axi_periph_0}]

# IP: bd/dsgn_can_test_intr/ip/dsgn_can_test_intr_rst_processing_system7_0_100M_0/dsgn_can_test_intr_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_test_intr_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==dsgn_can_test_intr_rst_processing_system7_0_100M_0}]

# IP: bd/dsgn_can_test_intr/ip/dsgn_can_test_intr_auto_pc_0/dsgn_can_test_intr_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsgn_can_test_intr_auto_pc_0 || ORIG_REF_NAME==dsgn_can_test_intr_auto_pc_0}]

# XDC: bd/dsgn_can_test_intr/ip/dsgn_can_test_intr_processing_system7_0_0/dsgn_can_test_intr_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_test_intr_processing_system7_0_0 || ORIG_REF_NAME==dsgn_can_test_intr_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/dsgn_can_test_intr/ip/dsgn_can_test_intr_axi_gpio_0_0/dsgn_can_test_intr_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_test_intr_axi_gpio_0_0 || ORIG_REF_NAME==dsgn_can_test_intr_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/dsgn_can_test_intr/ip/dsgn_can_test_intr_axi_gpio_0_0/dsgn_can_test_intr_axi_gpio_0_0_ooc.xdc

# XDC: bd/dsgn_can_test_intr/ip/dsgn_can_test_intr_axi_gpio_0_0/dsgn_can_test_intr_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_test_intr_axi_gpio_0_0 || ORIG_REF_NAME==dsgn_can_test_intr_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/dsgn_can_test_intr/ip/dsgn_can_test_intr_rst_processing_system7_0_100M_0/dsgn_can_test_intr_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_test_intr_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==dsgn_can_test_intr_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/dsgn_can_test_intr/ip/dsgn_can_test_intr_rst_processing_system7_0_100M_0/dsgn_can_test_intr_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dsgn_can_test_intr_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==dsgn_can_test_intr_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/dsgn_can_test_intr/ip/dsgn_can_test_intr_rst_processing_system7_0_100M_0/dsgn_can_test_intr_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/dsgn_can_test_intr/ip/dsgn_can_test_intr_auto_pc_0/dsgn_can_test_intr_auto_pc_0_ooc.xdc

# XDC: bd/dsgn_can_test_intr/dsgn_can_test_intr_ooc.xdc
